apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.deployment.namespace }}
  name: {{ include "golang-chart.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: golang-application
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: golang-application
    spec:
      containers:
      - image: mar3tin8/pintu-golang:1
        imagePullPolicy: Always
        name: golang-application
        ports:
        - containerPort: 8080