apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.deployment.namespace }}
  name: {{ include "golang-chart.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: golang-application
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: golang-application
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: golang-application
        ports:
        - containerPort: 8080 # Expose the port your application listens on