apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.service.namespace }}
  name: {{ include "golang-chart.fullname" . }}
spec:
  ports:
    - port: 80 # Expose port 80 for external access
      targetPort: 8080 # Route traffic to port 8080 on your pods
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: golang-application