apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.service.namespace }}
  name: {{ include "golang-chart.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: golang-application