pipeline:
  - trigger_mode: MANUAL
    trigger_condition: ALWAYS
    ref_name: "main"
    actions:
      - action: "Run npm install"
        type: "BUILD"
        working_directory: "/app/service-a"
        docker_image_name: "node:latest"
        execute_commands:
          - "npm install"

      - action: "Build Docker image"
        type: "BUILD"
        working_directory: "/app/service-a"
        docker_image_name: "docker:19.03.13"
        execute_commands:
          - "docker build -t mar3tin8/nodejs-app:latest ."

      - action: "Push Docker image to Docker Hub"
        type: "BUILD"
        working_directory: "/app/service-a"
        docker_image_name: "docker:19.03.13"
        execute_commands:
          - "docker login -u mar3tin8 -p $DOCKERHUB_PASSWORD"
          - "docker push mar3tin8/service-a:latest"